// Code generated by protoc-gen-go. DO NOT EDIT.
// source: report.proto

package report

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import admin "github.com/piyush2206/go-domain-driven-design/admin"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReqReportStudent struct {
	ClassId              string   `protobuf:"bytes,1,opt,name=classId,proto3" json:"classId,omitempty"`
	StudentId            string   `protobuf:"bytes,2,opt,name=studentId,proto3" json:"studentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqReportStudent) Reset()         { *m = ReqReportStudent{} }
func (m *ReqReportStudent) String() string { return proto.CompactTextString(m) }
func (*ReqReportStudent) ProtoMessage()    {}
func (*ReqReportStudent) Descriptor() ([]byte, []int) {
	return fileDescriptor_report_ab7c2db2a628dbe3, []int{0}
}
func (m *ReqReportStudent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqReportStudent.Unmarshal(m, b)
}
func (m *ReqReportStudent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqReportStudent.Marshal(b, m, deterministic)
}
func (dst *ReqReportStudent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqReportStudent.Merge(dst, src)
}
func (m *ReqReportStudent) XXX_Size() int {
	return xxx_messageInfo_ReqReportStudent.Size(m)
}
func (m *ReqReportStudent) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqReportStudent.DiscardUnknown(m)
}

var xxx_messageInfo_ReqReportStudent proto.InternalMessageInfo

func (m *ReqReportStudent) GetClassId() string {
	if m != nil {
		return m.ClassId
	}
	return ""
}

func (m *ReqReportStudent) GetStudentId() string {
	if m != nil {
		return m.StudentId
	}
	return ""
}

type ResReportStudent struct {
	Class                *admin.ClassInfo `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	Report               []*StudentReport `protobuf:"bytes,2,rep,name=report,proto3" json:"report,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ResReportStudent) Reset()         { *m = ResReportStudent{} }
func (m *ResReportStudent) String() string { return proto.CompactTextString(m) }
func (*ResReportStudent) ProtoMessage()    {}
func (*ResReportStudent) Descriptor() ([]byte, []int) {
	return fileDescriptor_report_ab7c2db2a628dbe3, []int{1}
}
func (m *ResReportStudent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResReportStudent.Unmarshal(m, b)
}
func (m *ResReportStudent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResReportStudent.Marshal(b, m, deterministic)
}
func (dst *ResReportStudent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResReportStudent.Merge(dst, src)
}
func (m *ResReportStudent) XXX_Size() int {
	return xxx_messageInfo_ResReportStudent.Size(m)
}
func (m *ResReportStudent) XXX_DiscardUnknown() {
	xxx_messageInfo_ResReportStudent.DiscardUnknown(m)
}

var xxx_messageInfo_ResReportStudent proto.InternalMessageInfo

func (m *ResReportStudent) GetClass() *admin.ClassInfo {
	if m != nil {
		return m.Class
	}
	return nil
}

func (m *ResReportStudent) GetReport() []*StudentReport {
	if m != nil {
		return m.Report
	}
	return nil
}

type StudentReport struct {
	StudentInfo          *admin.StudentInfo `protobuf:"bytes,1,opt,name=studentInfo,proto3" json:"studentInfo,omitempty"`
	GrandTotal           float64            `protobuf:"fixed64,3,opt,name=grandTotal,proto3" json:"grandTotal,omitempty"`
	GrandTotalMarks      float64            `protobuf:"fixed64,4,opt,name=grandTotalMarks,proto3" json:"grandTotalMarks,omitempty"`
	Percent              float64            `protobuf:"fixed64,5,opt,name=percent,proto3" json:"percent,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StudentReport) Reset()         { *m = StudentReport{} }
func (m *StudentReport) String() string { return proto.CompactTextString(m) }
func (*StudentReport) ProtoMessage()    {}
func (*StudentReport) Descriptor() ([]byte, []int) {
	return fileDescriptor_report_ab7c2db2a628dbe3, []int{2}
}
func (m *StudentReport) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentReport.Unmarshal(m, b)
}
func (m *StudentReport) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentReport.Marshal(b, m, deterministic)
}
func (dst *StudentReport) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentReport.Merge(dst, src)
}
func (m *StudentReport) XXX_Size() int {
	return xxx_messageInfo_StudentReport.Size(m)
}
func (m *StudentReport) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentReport.DiscardUnknown(m)
}

var xxx_messageInfo_StudentReport proto.InternalMessageInfo

func (m *StudentReport) GetStudentInfo() *admin.StudentInfo {
	if m != nil {
		return m.StudentInfo
	}
	return nil
}

func (m *StudentReport) GetGrandTotal() float64 {
	if m != nil {
		return m.GrandTotal
	}
	return 0
}

func (m *StudentReport) GetGrandTotalMarks() float64 {
	if m != nil {
		return m.GrandTotalMarks
	}
	return 0
}

func (m *StudentReport) GetPercent() float64 {
	if m != nil {
		return m.Percent
	}
	return 0
}

func init() {
	proto.RegisterType((*ReqReportStudent)(nil), "report.ReqReportStudent")
	proto.RegisterType((*ResReportStudent)(nil), "report.ResReportStudent")
	proto.RegisterType((*StudentReport)(nil), "report.StudentReport")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReportClient is the client API for Report service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReportClient interface {
	Report(ctx context.Context, in *ReqReportStudent, opts ...grpc.CallOption) (*ResReportStudent, error)
}

type reportClient struct {
	cc *grpc.ClientConn
}

func NewReportClient(cc *grpc.ClientConn) ReportClient {
	return &reportClient{cc}
}

func (c *reportClient) Report(ctx context.Context, in *ReqReportStudent, opts ...grpc.CallOption) (*ResReportStudent, error) {
	out := new(ResReportStudent)
	err := c.cc.Invoke(ctx, "/report.Report/Report", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReportServer is the server API for Report service.
type ReportServer interface {
	Report(context.Context, *ReqReportStudent) (*ResReportStudent, error)
}

func RegisterReportServer(s *grpc.Server, srv ReportServer) {
	s.RegisterService(&_Report_serviceDesc, srv)
}

func _Report_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqReportStudent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReportServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/report.Report/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReportServer).Report(ctx, req.(*ReqReportStudent))
	}
	return interceptor(ctx, in, info, handler)
}

var _Report_serviceDesc = grpc.ServiceDesc{
	ServiceName: "report.Report",
	HandlerType: (*ReportServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Report",
			Handler:    _Report_Report_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "report.proto",
}

func init() { proto.RegisterFile("report.proto", fileDescriptor_report_ab7c2db2a628dbe3) }

var fileDescriptor_report_ab7c2db2a628dbe3 = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x51, 0xc1, 0x4e, 0x2a, 0x31,
	0x14, 0xcd, 0xc0, 0x83, 0x27, 0x45, 0x23, 0x69, 0x62, 0xd2, 0x10, 0x62, 0xc8, 0x2c, 0xcc, 0x6c,
	0x66, 0xc6, 0x8c, 0xc6, 0xad, 0x0b, 0x57, 0x98, 0xe8, 0xa2, 0xb8, 0x70, 0x5b, 0x68, 0x19, 0x1a,
	0xa1, 0x77, 0x6c, 0x8b, 0x89, 0x5b, 0x7f, 0xc1, 0xaf, 0xf0, 0x7b, 0xfc, 0x05, 0x3f, 0xc4, 0xd0,
	0x76, 0x84, 0x61, 0xd3, 0xf4, 0xdc, 0x73, 0x7a, 0xee, 0xbd, 0xa7, 0xe8, 0x58, 0x8b, 0x0a, 0xb4,
	0xcd, 0x2a, 0x0d, 0x16, 0x70, 0xd7, 0xa3, 0xe1, 0x6d, 0x29, 0xed, 0x72, 0x33, 0xcb, 0xe6, 0xb0,
	0xce, 0x2b, 0xf9, 0xbe, 0x31, 0xcb, 0xa2, 0xb8, 0xbc, 0xc9, 0x4b, 0x48, 0x39, 0xac, 0x99, 0x54,
	0x29, 0xd7, 0xf2, 0x4d, 0xa8, 0x94, 0x0b, 0x23, 0x4b, 0x95, 0x33, 0xbe, 0x96, 0xe1, 0xf4, 0x46,
	0xc3, 0x51, 0x09, 0x50, 0xae, 0x44, 0xce, 0x2a, 0x99, 0x33, 0xa5, 0xc0, 0x32, 0x2b, 0x41, 0x19,
	0xcf, 0xc6, 0xf7, 0x68, 0x40, 0xc5, 0x2b, 0x75, 0xbd, 0xa6, 0x76, 0xc3, 0x85, 0xb2, 0x98, 0xa0,
	0xff, 0xf3, 0x15, 0x33, 0x66, 0xc2, 0x49, 0x34, 0x8e, 0x92, 0x1e, 0xad, 0x21, 0x1e, 0xa1, 0x9e,
	0xf1, 0xa2, 0x09, 0x27, 0x2d, 0xc7, 0xed, 0x0a, 0xb1, 0xdc, 0x7a, 0x99, 0xa6, 0xd7, 0x05, 0xea,
	0xb8, 0xc7, 0xce, 0xa9, 0x5f, 0x0c, 0x32, 0x3f, 0xda, 0x9d, 0x33, 0x54, 0x0b, 0xa0, 0x9e, 0xc6,
	0x29, 0x0a, 0x0b, 0x93, 0xd6, 0xb8, 0x9d, 0xf4, 0x8b, 0xb3, 0x2c, 0xa4, 0x11, 0x8c, 0xbc, 0x2b,
	0x0d, 0xa2, 0xf8, 0x2b, 0x42, 0x27, 0x0d, 0x06, 0x5f, 0xa3, 0x7e, 0x3d, 0x89, 0x5a, 0x40, 0x68,
	0x87, 0x43, 0xbb, 0xe9, 0x8e, 0xa1, 0xfb, 0x32, 0x7c, 0x8e, 0x50, 0xa9, 0x99, 0xe2, 0x4f, 0x60,
	0xd9, 0x8a, 0xb4, 0xc7, 0x51, 0x12, 0xd1, 0xbd, 0x0a, 0x4e, 0xd0, 0xe9, 0x0e, 0x3d, 0x30, 0xfd,
	0x62, 0xc8, 0x3f, 0x27, 0x3a, 0x2c, 0x6f, 0x43, 0xab, 0x84, 0x9e, 0x0b, 0x65, 0x49, 0xc7, 0x29,
	0x6a, 0x58, 0x3c, 0xa3, 0x6e, 0x98, 0xf1, 0xf1, 0xef, 0x46, 0xea, 0xf5, 0x0e, 0xc3, 0x1f, 0xee,
	0x31, 0xcd, 0x28, 0xe3, 0xc1, 0xc7, 0xf7, 0xcf, 0x67, 0x0b, 0xe1, 0xa3, 0xdc, 0x2b, 0xcc, 0xac,
	0xeb, 0xfe, 0xf0, 0xea, 0x37, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x0f, 0x57, 0x6a, 0x3a, 0x02, 0x00,
	0x00,
}
